### PR TITLE
general checks and improvements

### PR DESCRIPTION
**Pull request by d3liaa**
Hi Christian,
i made an overall check and adjusted some things.
For example:
- Logo to big in detail view ->i put the width undefined in the component to make it adjustable in the detail view but left 100% for the edit view
- fixed municipalityIdcell -> it showed a dropdown instead of the id

### CODE REVIEW

**Comment by gappc** [comment]
Hi @d3liaa, thank you for the PR. Since there are a lot of changes, I'd like to have a meeting with you to take a look at the changes together. It would probably be a good idea to have @pkritzinger and @RudiThoeni in the meeting as well. I'll write an email

**Comment by d3liaa** [comment]
Yes of course! I will be available from the first of march onwards!

Have a nice weekend,
Delia :)

Il giorno sab 25 feb 2023 alle 13:21 gappc ***@***.***> ha
scritto:

**Comment by sseppi** [comment]
@gappc please invite me at the meeting, I will add then Rudi in case of need.

**Comment by gappc** [comment]
@sseppi yes I can invite you, but we need to wait for Delia.

**Comment by gappc** [comment]
@d3liaa I saw that your branch has merge conflicts. Please solve them. Further, please note that you should not change Article and EventShort, because those two are already ready.

Thank you

**Comment by d3liaa** [comment]
Understood! I will fix everything as soon as I get back!
Have a nice day,
Delia:)

Il giorno lun 27 feb 2023 alle 09:04 gappc ***@***.***> ha
scritto:

**Comment by gappc** [comment]
Hi @d3liaa, do you have updates regarding this PR?

**Comment by d3liaa** [comment]
Hi @gappc i was waiting for your return, so we could continue the meeting and finish analyzing the PR together. Do you want to schedule a meeting?

**Pull request merged**
