### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by gappc**
Update project dependencies:

- vue to 3.4
- vite and related build tools to current version
- axios to 1.65 to fix security vulnerabilities
- eslint to fix security vulnerabilities
- caniuse to use latest browser statistics

### CODE REVIEW

**Comment by gappc** [comment]
@RudiThoeni @dulvui from my point of view this PR is ready to be merged, thx

**Comment by RudiThoeni** [comment]
so let's merge also this :)

**Comment by gappc** [comment]
@RudiThoeni nice, thx :)

**Comment by gappc** [comment]
@MatteoBiasi @a-crea @RudiThoeni @dulvui @d3liaa this PR changed updated some project dependencies. Please update your node_modules by running `npm run i`.

**Pull request merged**
