### PR TITLE
Feat/delete record from table view rebase

### LINKED ISSUE #460: As an Open Data Hub Content Editor I want to be able to delete the content I'm responsible for, to remove wrong records.
We need to implement as soon as possible the delete functionality, since some user are asking for it.

One idea could be to add a button `Delete` in the right column in Table view.

Shall we add a the delete functionality also in the detail, edit and raw view?

### PR DESCRIPTION
**Pull request by a-crea**
This PR resolves #460

### CODE REVIEW

**Comment by a-crea** [comment]
Hi @gappc , please let me know if everything is in order. I had to create new branches and rearrange the code, so now everything should proceed smoothly :)

**Comment by gappc** [comment]
Hey @a-crea, impressive work, well done :+1: 

I asked @RudiThoeni if I could do some merges during the weekend, he said ok, so if you want I can merge this PR

**Comment by gappc** [comment]
One thing came to my mind: would it be possible to extract the `delete` implementation from [TableView.vue](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/blob/0ada02e1b581fbe858c3a795deb6ccae5dbaffb7/databrowser/src/domain/datasets/ui/tableView/TableView.vue) into something like `useTableDelete`? That would move complexity out of the TableView.vue

**Comment by a-crea** [comment]
@gappc would it cause problems to merge it as it is and then to apply the improvement? Each time I try to rebase it breaks the commits history... otherwise I could need your help to understand what is happening :/

I'm on Node 18 as suggested

**Comment by gappc** [comment]
@a-crea I think we can merge it now and apply the improvements afterwards. @RudiThoeni could you please merge this PR?

@a-crea given that rebasing causes trouble, we could schedule a meeting where we can take a look at how to fix errors associated with it.

**Comment by RudiThoeni** [comment]
done

**Comment by gappc** [comment]
@a-crea could you please take a look at the problem? Thx

**Pull request merged**
