### PR TITLE
Fix/optimizations and fixes pr 596

### PR DESCRIPTION
**Pull request by a-crea**
This PR fixes refer to https://github.com/noi-techpark/it.bz.opendatahub.databrowser/pull/596#issuecomment-2381437866

Remaining points for discussion:
- Referenced attributes not displaying when the toggle is disabled
- Potential confusion with the toggle text: the wording has been changed, but needs confirmation
- Deciding between using a Popover or Tooltip component"

### CODE REVIEW

**Comment by a-crea** [comment]
@gappc, in guideline.md, should I mention avoiding TooltipCustom because it will be deprecated (and use Popover instead) under the "Coding Style" section, or should I create a new section, such as "Additional Information"?

**Comment by gappc** [comment]
@a-crea good question. What you say if we create a section "deprecations" (or something like that) and add there for any  deprecation information a subsection where we shortly explain the what, why and alternative?

**Comment by a-crea** [comment]
@gappc guidelines updated :) 
If you agree I think we can consider the PR ready to merge :)

**Comment by sseppi** [comment]
@gappc I think that can be merged too, please notify @RudiThoeni if you agree too,

**Pull request merged**
