### PR TITLE
TO REMOVE: WIP: fix: avoid fetch with no queryFn. Parse showAddNewValue as boolean.

### PR DESCRIPTION
**Pull request by a-crea**
This PR refers to #452 and #453

### CODE REVIEW

**Comment by gappc** [comment]
@a-crea I've checked the usage of the `SelectWithOptionsCell` component and the `url` parameter is nowhere used. Therefore I removed the corresponding code from the component in my PR #482 - which is also kind of a fix ;) (see https://github.com/noi-techpark/it.bz.opendatahub.databrowser/blob/1e602080b791bff5656f27958f64238f46dfcdd4/databrowser/src/domain/cellComponents/components/cells/selectWithOptionsCell/SelectWithOptionsCell.vue).

If it's ok for you, we could close this PR here.

**Comment by a-crea** [comment]
@gappc I double checked, it should be used in the metaData.sharedView.ts, Dataspace field

**Comment by gappc** [comment]
@a-crea you are completely right, thanks for pointing that out.

I unified the remote select option fetching between the components in this two commits from PR #482: https://github.com/noi-techpark/it.bz.opendatahub.databrowser/pull/482/commits/d0a5128a62277b9a02d40a3a09c358078eb844b2 and https://github.com/noi-techpark/it.bz.opendatahub.databrowser/pull/482/commits/afa77e05b1113bc188b1753b605cf337cef35a87

The fix relevant to the queryFn bug can be found here: https://github.com/noi-techpark/it.bz.opendatahub.databrowser/blob/afa77e05b1113bc188b1753b605cf337cef35a87/databrowser/src/domain/cellComponents/components/cells/selectWithOptionsCell/SelectWithOptionsCell.vue#L98-L109

Is it ok if we wait until PR #482 gets merged and decide then what to to with this PR? I fear that we could step on each others toes, mainly because #482 is so big (this shows why it is a bad idea to have huge PRs ;) )

**Comment by gappc** [comment]
PR #482 was now merged and is online. Please check if it fixes the problem associated with this PR, maybe we can just close the PR

**Comment by a-crea** [comment]
@gappc with #482 merged we can ignore and close this PR, I checked the reported issues using the development branch, I found no error :)

**Pull request closed without merging**
