### PR TITLE
documentation draft

### PR DESCRIPTION
**Pull request by d3liaa**

### CODE REVIEW

**Comment by gappc** [comment]
Hi @d3liaa, nice work :+1: How should we proceed with this PR?

**Comment by d3liaa** [comment]
hi @gappc, I will work on the documentation with the material we discussed in the last meeting. We could organize another meeting to continue with the topics we didn't have time to cover. Let me know when you would prefer :)
I made a draft PR so everybody could see the progress and fact-check or give suggestions.

**Comment by gappc** [comment]
@d3liaa very well written, thank you for this outstanding work :+1: 

I found some minor spelling issues, I'd be glad if you could fix them. After that I think the PR is ready to be merged. @sseppi what do you say?

**Comment by mrabans** [comment]
@gappc please merge

**Comment by gappc** [comment]
Closing, because it is resolved in #428

**Pull request closed without merging**
