### PR TITLE
Feat/target blank header links

### PR DESCRIPTION
**Pull request by a-crea**
This PR add _blank target to external header links. It also includes the popover menu for login/register on desktop.

### CODE REVIEW

**Comment by gappc** [comment]
@a-crea the PR looks good to me, the only thing that we should discuss is the usage of the `IconParser`, e.g. [here](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/blob/8c6dc51f40e12e8a4440f13b6b987c2615e1e0ef/databrowser/src/domain/auth/ProfileButton.vue#L13)

The problem is related to issue #507, which shows that we have lots of warnings during compilation due to the mixed usage of `IconParser` (with dynamic icon imports) and static import of icon components. It seems that we need to stick to either the dynamic or static import. If you want, please tell your opinion in #507, thx

**Comment by RudiThoeni** [comment]
is this PR ready to merge?

**Comment by MatteoBiasi** [comment]
@gappc Since IconParser is present in the code for more than one year, if @sseppi agrees I suggest to open a separate issue for this and discuss it separately, so meanwhile we can close this one.

**Comment by gappc** [comment]
@MatteoBiasi yes, let's discuss this in a separate issue (quick note: the warnings showed up after the update of `vite` in 5bd7e392d8dfd1036e8cd8d613817ba859eccbb6)

**Comment by gappc** [comment]
@sseppi I've created issue #507, lets move the discussion there

**Comment by sseppi** [comment]
> @sseppi @MatteoBiasi @a-crea I've created issue #507, lets move the discussion there

OK, super! Thank you!

**Pull request merged**
