### PR TITLE
TO DELETE: WIP: feat: delete record from table view

### PR DESCRIPTION
**Pull request by a-crea**
This PR refers to #460

### CODE REVIEW

**Comment by gappc** [comment]
@a-crea since PR #482 got merged, lots of stuff changed. Please check for merge conflicts. If you have any questions, just let me know

**Comment by a-crea** [comment]
@gappc I'm still facing some problems with the rebase, please await my confirmation for the PRs, I'm almost there :)

**Comment by a-crea** [comment]
@gappc we can ignore and close this PR :) Please consider the #489

**Comment by sseppi** [comment]
I close without mergin this issue, since a-crea created a new one for the same features.

**Pull request closed without merging**
