### PR TITLE
Feat/file upload modal

### PR DESCRIPTION
**Pull request by a-crea**
This pull request includes the new file upload language settings modal.

### CODE REVIEW

**Comment by gappc** [comment]
@a-crea Thank you for this PR

Unfortunately it doesn't satisfy all checks (see https://github.com/noi-techpark/it.bz.opendatahub.databrowser/actions/runs/6563367797/job/17827429525?pr=431) and can therefor not be merged.

I think the problems are related to missing REUSE license headers in new files. Please take a look at other existing files and see how such headers look like. Then, please add the header to all related files.

**Comment by gappc** [comment]
@a-crea thank you for this PR

There still seems to be a bug, where I'm not able to add languages (see screenshot)

image

Steps to reproduce:

- start the project locally (npm run dev)
- open e.g. http://localhost:3000/dataset/edit/tourism/v1/EventShort/e98699d1-0ab0-4197-aa74-a9226d6e821c?language=it#files
- open the details of any table entry
- click on the Link "Update language settings"

=> the popup appears, but there is no way to add languages

In my opinion, all languages should be shown such that a user can select languages that were not selected before

----------------------------------

There seems to be another (related?) bug, that happens when more than one documents get uploaded. Ifone wants to change the language info without reloading the page, no language is shown at all in the popup

Steps to reproduce:

- start the project locally (npm run dev)
- open e.g. http://localhost:3000/dataset/edit/tourism/v1/EventShort/e98699d1-0ab0-4197-aa74-a9226d6e821c?language=it#files
- upload more than one file
- set document names
- click "Save & next"
- open the details of one of the the new uploaded file
- click on the Link "Update language settings"

=> the popup appears, but there is no language shown at all



Please take a look at these issues, thx

**Comment by MatteoBiasi** [comment]
@gappc this has been separated in another issue: https://github.com/noi-techpark/it.bz.opendatahub.databrowser/issues/438. For this PR this behaviour it's fine.

**Comment by gappc** [comment]
@MatteoBiasi I had the impression that it should be possible to add languages and #438 was there to discuss if the language assignment should be modified (e.g. provide delete / add buttons)

@sseppi if the behavior implemented in this PR is fine, we can merge it

**Comment by sseppi** [comment]
> @MatteoBiasi I had the impression that it should be possible to add languages and #438 was there to discuss if the language assignment should be modified (e.g. provide delete / add buttons). The main problem with this implementation is, that it is impossible to add languages after an upload was saved.
> 
> @sseppi if the behavior implemented in this PR is fine, we can merge it

@gappc @MatteoBiasi I agree that the behaviour isn't perfet at the moment, but I need to go online as soon as possible with this new feature. So I would suggest to do compromise, go online with this PR and implement as soon as possibel the changes included in the issue #438

**Pull request merged**
