### PR TITLE
TO DELETE: WIP: feat: update header style. Update header and footer logo.

### PR DESCRIPTION
**Pull request by a-crea**
This PR refers to #437

### CODE REVIEW

**Comment by a-crea** [comment]
@gappc I'm facing errors with the rebase, I will create new PRs and rename the broken ones "TO REMOVE".
Otherwise, I could close the broken ones; whichever is more convenient for you. :)

**Comment by gappc** [comment]
@a-crea just open up new PRs, we'll delete the old ones

**Comment by gappc** [comment]
@a-crea since PR #482 got merged, lots of stuff changed. Please check for merge conflicts. If you have any questions, just let me know

**Comment by a-crea** [comment]
@gappc we can ignore and close this PR :) Refers to #491

**Comment by sseppi** [comment]
Since @a-crea created a new PR, I close without merging this PR.

**Pull request closed without merging**
