### PR TITLE
Feature update home

### PR DESCRIPTION
**Pull request by gappc**

### CODE REVIEW

**Comment by gappc** [comment]
Hey @RudiThoeni, could you please take a look at this PR? I must confess, its a big one, sry about that ;)

**Comment by RudiThoeni** [comment]
Hi @gappc 
Seems all good, lets merge and see how the updated home it look likes ;)

One thing maybe tof ix before, links to the official opendatahub page should always link to opendatahub.com instead of bz.it

**Comment by gappc** [comment]
Hi @RudiThoeni, I fixed the links

**Review by RudiThoeni — APPROVED** [review]

**Comment by RudiThoeni** [comment]
@gappc  great thx, go on or should i merge?

**Comment by gappc** [comment]
@RudiThoeni thx, I'll merge it

**Pull request merged**
