### PR TITLE
start editView

### PR DESCRIPTION
**Pull request by ila131**
Hey Christian,
I started the Activities&POI editView, let me know if everything is working as expected :)

Thank you very much,

Ilaria

### CODE REVIEW

**Comment by gappc** [comment]
Hi @ila131, I found two things that should be fixed:

- [Active on ODH](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/blob/71e830fdf1f158943a96197537bf344d20a8c46e/databrowser/src/config/tourism/odhActivityPoi/odhActivityPoi.editView.ts#L259) should most probably be "Active on Open Data Hub" - I just merged a PR from you that fixes that stuff in other places ;)
- some of the `ToggleCell` elements should be read-only, [Active on ODH](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/blob/71e830fdf1f158943a96197537bf344d20a8c46e/databrowser/src/config/tourism/odhActivityPoi/odhActivityPoi.editView.ts#L259) being one example. You can take a look at [this configuration](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/blob/development/databrowser/src/config/tourism/district/district.editView.ts#L97) to see how to make a `ToggleCell` read-only

I can not say if the rest of the configuration is correct from an organizational perspective, please ask @pkritzinger or @sseppi to check it.

**Comment by ila131** [comment]
Hey @gappc ,
thank you very much for your feedback :)

Ilaria

**Comment by pkritzinger** [comment]
Hi @ila131 
Is there anything I can help you with or have all the open topics been resolved?

**Comment by ila131** [comment]
Hey @pkritzinger now I am fixing the code with the changes that @gappc told me and then I will reach out to you with a new PR :)

Have a nice day, 

Ilaria

**Pull request closed without merging**
