### PR TITLE
TO DELETE: Feat/delete record from table view

### LINKED ISSUE #460: As an Open Data Hub Content Editor I want to be able to delete the content I'm responsible for, to remove wrong records.
We need to implement as soon as possible the delete functionality, since some user are asking for it.

One idea could be to add a button `Delete` in the right column in Table view.

Shall we add a the delete functionality also in the detail, edit and raw view?

### PR DESCRIPTION
**Pull request by a-crea**
This PR resolves #460

### CODE REVIEW

**Comment by a-crea** [comment]
@gappc is there a way to easily reload the current dataset?
Example: I'm in the event short table view, I delete a record and the table reloads. I managed to achieve that before the major merge of #482, but there should be an even easier and cleaner way now.

**Comment by gappc** [comment]
Ah, I think that's related to [TanQuery](https://tanstack.com/query/latest) that is used to fetch data. Internally it uses a caching algorithm, keyed by the URL. I think the solution could be around here: https://tanstack.com/query/latest/docs/react/guides/query-invalidation

Could you please provide me the steps to reproduce the problem, maybe using your branch?

**Comment by a-crea** [comment]
@gappc we can ignore and close this PR :) Please consider the #489

**Comment by sseppi** [comment]
I close without mergin this issue, since a-crea created a new one for the same features.

**Pull request closed without merging**
