### PR TITLE
Implement support for datasets from mobility domain

### PR DESCRIPTION
**Pull request by gappc**
This single giant commit changes a lot of stuff. First and most important, it adds support for datasets from the mobility domain. During this process, a lot of code was refactored and improved. The most important other changes are:

- rename config property "fields" to "objectMapping" to help in understanding
- rename config property "listFields" to "arrayMapping" to help in understanding
- rework dataset config generation and computation to simplify the code
- rework navigation and pagination for the table view
- simplify data fetching and processing
- unify the way how cell components fetch data
- relocate files and folder inside the "domain" folder
- add / improve components
- fix bugs in existing of components

... and lots of other stuff

### CODE REVIEW

**Comment by gappc** [comment]
Whoever is going to take a look at this PR: please don't shoot me

**Comment by RudiThoeni** [comment]
@gappc Hi i had to merge the PR from a-crea first (strategy who opens first, get merged first ;) )
Can you resolve this conflict then i will merge this huge PR
thx

**Comment by gappc** [comment]
@RudiThoeni I fixed the problems, the PR should now be ready to merge

**Review by RudiThoeni — APPROVED** [review]
blind approval 👍

**Pull request merged**
