### PR TITLE
New GpsPoints cell component

### PR DESCRIPTION
**Pull request by BlueRyse**
Hi @gappc, I changed the gps list cell component to comply with the new GPSPoints data on the tourism API. I already tried it and it works. When using it in a config file, it should be used like this:

`{

      title: 'GPS Data',
      component: CellComponent.GpsListCell,
      class: 'w-48',
      fields: {

        type: 'GpsPoints.position.Gpstype',
        latitude: 'GpsPoints.position.Latitude',
        longitude: 'GpsPoints.position.Longitude',
        altitude: 'GpsPoints.position.Altitude',
        altitudeUnit: 'GpsPoints.position.AltitudeUnitofMeasure'
      },

    },`

Of course it's most likely not perfect, so please let me know if we can improve something before merging.

Thank you.

### CODE REVIEW

**Comment by BlueRyse** [comment]
@gappc PR is now ready for review. Ready to hear some feedback, if any.

One thing I would consider to change is the small bar at the bottom of the component, but I'm not sure if and how to proceed. Is that part of CSS?

Screenshot from 2022-10-11 19-11-48

**Comment by gappc** [comment]
HI @BlueRyse, your commit looks good. There is just one minor thing, the component **GpsPointsCell.vue** seems to exist twice:

- https://github.com/noi-techpark/it.bz.opendatahub.databrowser/blob/9c1d972d1ec0267d35e2952f8ad4ae59064a2727/databrowser/src/domain/cellComponents/components/cells/gpsListCell/GpsPointsCell.vue
- https://github.com/noi-techpark/it.bz.opendatahub.databrowser/blob/9c1d972d1ec0267d35e2952f8ad4ae59064a2727/databrowser/src/domain/cellComponents/components/cells/gpsPointsCell/GpsPointsCell.vue

Please remove one of the implementations above and adjust the imports if necessary (in my opinion you could remove the whole gpsListCell folder), than we can merge the PR

**Comment by gappc** [comment]
> @gappc PR is now ready for review. Ready to hear some feedback, if any.
> 
> One thing I would consider to change is the small bar at the bottom of the component, but I'm not sure if and how to proceed. Is that part of CSS?
> 
> Screenshot from 2022-10-11 19-11-48

It seems to be a vertical scrollbar. If that guess is right, the container is probably to narrow, try to make it wider

**Comment by gappc** [comment]
@BlueRyse thank you for the fix :)

I missed one more thing on my last review, there is a comments left in **GpsPointsCell.vue** that we don't need anymore: https://github.com/noi-techpark/it.bz.opendatahub.databrowser/blob/11259e8b485f9d8d9bb8963fa779f8e3e44936d4/databrowser/src/domain/cellComponents/components/cells/gpsPointsCell/GpsPointsCell.vue#L30-L34

Please remove that comment (sry for overlooking it the first time)

**Comment by BlueRyse** [comment]
> @BlueRyse thank you for the fix :)
> 
> I missed one more thing on my last review, there is a comments left in **GpsPointsCell.vue** that we don't need anymore:
> 
> https://github.com/noi-techpark/it.bz.opendatahub.databrowser/blob/11259e8b485f9d8d9bb8963fa779f8e3e44936d4/databrowser/src/domain/cellComponents/components/cells/gpsPointsCell/GpsPointsCell.vue#L30-L34
> 
> Please remove that comment (sry for overlooking it the first time)

@gappc Yes, it was deleted in the gpsListCell/GpsPointsCell.vue file, but not in this one :)

Comment is now deleted!

**Comment by gappc** [comment]
@BlueRyse perfect, thank you :+1:

**Pull request merged**
